# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ashwin Sinha
email: ash@ds.gg
description: > # this means to ignore newlines until "baseurl:"
  Ashwin Sinha's website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ash.wine" # the base hostname & protocol for your site
twitter_username: ashwinning
github_username:  ashwinning

# Build settings
markdown: kramdown
